image: archlinux
packages:
  - buildah
sources:
  - https://git.sr.ht/~robertgzr/easycaddy
secrets:
  - 9e73c7db-bf27-4921-a0fa-6a706c85f2cd
tasks:
  - build: |
      cd easycaddy
      ./make.sh build
  - deploy: |
      cd easycaddy
      du=`cat ~/.dockercreds | cut -d\: -f1`
      dp=`cat ~/.dockercreds | cut -d\: -f2`
      echo $dp | buildah login --username $du --password-stdin docker.io
      ./make.sh push # webhook
