image: 'fedora/30'
packages:
  - buildah
sources:
  - https://git.sr.ht/~robertgzr/easycaddy
secrets:
  - 985dd57c-ae11-46ee-9419-45ff06078c19
tasks:
  - build: |
      cd easycaddy
      ./make.sh build
  - deploy: |
      . ~/.easycaddy_secrets
      set +x
      buildah login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} docker.io
      set -x
      cd easycaddy
      ./make.sh push
      ./make.sh webhook
