image: archlinux
packages:
  - buildah
sources:
  - https://git.sr.ht/~robertgzr/easycaddy
secrets:
  - 299776af-3511-4b6c-8539-ac256471dcb0
tasks:
  - build: |
      cd easycaddy
      ./make.sh build
  - deploy: |
      cd easycaddy
      cat ~/.dockercreds | buildah login --username robertgzr --password-stdin docker.io
      ./make.sh push # webhook
