image: 'alpine/latest'
packages:
  - docker
  - make
sources:
  - https://git.sr.ht/~robertgzr/easycaddy
secrets:
  - 985dd57c-ae11-46ee-9419-45ff06078c19
tasks:
  - prepare: |
      rc-service docker start
  - do: |
      . ~/.easycaddy_secrets
      set +x
      sudo docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} docker.io
      set -x
      cd easycaddy
      sudo make container-multiarch
