language: minimal

services: 
  - docker

stages:
  - build
  - name: push
    if: branch = master

jobs:
  include:
    - stage: build
      name: "build for amd64"
      script:
        - make build.amd64

    - stage: build
      name: "build for armv7hf"
      script:
        - make build.armv7hf

    - stage: push
      name: "push to docker.io"
      script:
        - make push
