language: minimal

services:
  - docker

script:
  - BUILD='docker build' ./make.sh build

before_deploy:
  - echo "$DOCKER_PASSWORD" | $B login -u "$DOCKER_USERNAME" --password-stdin docker.io

deploy:
  provider: script
  script: PUSH='docker push' ./make.sh push webhook
  on:
    branch: master
